# Generated by Django 3.2.20 on 2023-08-16 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('category', models.CharField(choices=[('WEDDING', 'На свадьбу'), ('BIRTHDAY_PARTY', 'На день рождения'), ('WHATEVER', 'Пофиг')], default='WHATEVER', max_length=30, verbose_name='категория букета')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение букета')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'букет',
                'verbose_name_plural': 'букеты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='имя клиента')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region='RU', unique=True, verbose_name='телефон клиента')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'цветок',
                'verbose_name_plural': 'цветы',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='тип')),
                ('color', models.CharField(choices=[('YELLOW', 'Жёлтый'), ('RED', 'Красный'), ('GREEN', 'Зелёный'), ('ORANGE', 'Оранжевый'), ('BLUE', 'Синий'), ('PINK', 'Розовый'), ('BROWN', 'Коричневый'), ('РURPLE', 'Фиолетовый'), ('WHITE', 'Белый'), ('BLACK', 'Чёрный')], default='YELLOW', max_length=30, verbose_name='цвет')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'упаковка',
                'verbose_name_plural': 'упаковки',
            },
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='тип')),
                ('color', models.CharField(choices=[('YELLOW', 'Жёлтый'), ('RED', 'Красный'), ('GREEN', 'Зелёный'), ('ORANGE', 'Оранжевый'), ('BLUE', 'Синий'), ('PINK', 'Розовый'), ('BROWN', 'Коричневый'), ('РURPLE', 'Фиолетовый'), ('WHITE', 'Белый'), ('BLACK', 'Чёрный')], default='YELLOW', max_length=30, verbose_name='цвет')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'лента',
                'verbose_name_plural': 'ленты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=350, verbose_name='адрес доставки')),
                ('delivery_time', models.CharField(choices=[('URGENT', 'Как можно скорее'), ('t10_12', 'с 10:00 до 12:00'), ('t12_14', 'с 12:00 до 14:00'), ('t14_16', 'с 14:00 до 16:00'), ('t16_18', 'с 16:00 до 18:00'), ('t18_20', 'с 18:00 до 20:00')], default='URGENT', max_length=10, verbose_name='время доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('status', models.CharField(choices=[('TBA', 'На уточнении'), ('ASSEMBLING', 'Собирается'), ('DELIVERING', 'Доставляется'), ('DONE', 'Выполнен')], default='TBA', max_length=15, verbose_name='Статус заказа')),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Стоимость')),
                ('bouquet', models.ManyToManyField(related_name='orders', to='flowerapp.Bouquet', verbose_name='букет')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='flowerapp.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='FlowersSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('YELLOW', 'Жёлтый'), ('RED', 'Красный'), ('GREEN', 'Зелёный'), ('ORANGE', 'Оранжевый'), ('BLUE', 'Синий'), ('PINK', 'Розовый'), ('BROWN', 'Коричневый'), ('РURPLE', 'Фиолетовый'), ('WHITE', 'Белый'), ('BLACK', 'Чёрный')], default='YELLOW', max_length=30, verbose_name='оттенок цветка')),
                ('quantity', models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('flower', models.ManyToManyField(related_name='flowers_sets', to='flowerapp.Flower', verbose_name='цветок')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers_set',
            field=models.ManyToManyField(related_name='bouquets', to='flowerapp.FlowersSet', verbose_name='набор цветов'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='packaging',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquets', to='flowerapp.packaging', verbose_name='упаковка'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='ribbon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquets', to='flowerapp.ribbon', verbose_name='лента'),
        ),
    ]
