# Generated by Django 3.2.20 on 2023-08-16 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('YELLOW', 'Жёлтый'), ('RED', 'Красный'), ('GREEN', 'Зелёный'), ('ORANGE', 'Оранжевый'), ('BLUE', 'Синий'), ('PINK', 'Розовый'), ('BROWN', 'Коричневый'), ('РURPLE', 'Фиолетовый'), ('WHITE', 'Белый'), ('BLACK', 'Чёрный')], default='YELLOW', max_length=30, verbose_name='оттенок цветка')),
                ('quantity', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='количество')),
            ],
            options={
                'verbose_name': 'цветок букета',
                'verbose_name_plural': 'цветы букета',
            },
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='flowers_set',
        ),
        migrations.DeleteModel(
            name='FlowersSet',
        ),
        migrations.AddField(
            model_name='bouquetitem',
            name='bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_items', to='flowerapp.bouquet', verbose_name='букет'),
        ),
        migrations.AddField(
            model_name='bouquetitem',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquet_items', to='flowerapp.flower', verbose_name='цветок'),
        ),
    ]
