# Generated by Django 3.2.20 on 2023-08-17 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0002_auto_20230816_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='dont_update_price',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Не обновлять цену'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Цена'),
        ),
    ]
