# Generated by Django 3.2.20 on 2023-08-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0003_auto_20230817_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquets', to='flowerapp.packaging', verbose_name='упаковка'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='ribbon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquets', to='flowerapp.ribbon', verbose_name='лента'),
        ),
    ]
