# Generated by Django 3.2.20 on 2023-08-18 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0004_auto_20230817_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='высота, см'),
        ),
        migrations.AddField(
            model_name='bouquet',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ширина, см'),
        ),
    ]
