# Generated by Django 3.2.20 on 2023-08-20 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowerapp', '0006_order_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='дата и время заказа'),
        ),
    ]
